version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=YourStrong!Password123
      - POSTGRES_DB=customer_db
    ports:
      - "5432:5432"
    volumes:
      - ../Database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  mongo:
    image: mongo:4.2
    container_name: mongo
    environment:
      MONGO_INITDB_DATABASE: graylog
    volumes:
      - mongo_data:/data/db
    networks:
      - my_network
    ports:
      - "27017:27017"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: elasticsearch
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -Des.transport.cname_in_publish_address=true"
    networks:
      - my_network
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - es_data:/usr/share/elasticsearch/data

  graylog:
    image: graylog/graylog:4.1
    container_name: graylog
    volumes:
      - graylog_data:/usr/share/graylog/data/journal
    environment:
      - GRAYLOG_PASSWORD_SECRET=MyRandomPassword123
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - mongo
      - elasticsearch
    networks:
      - my_network
    ports:
      # Graylog web interface and REST API
      - "9000:9000"
      # Syslog TCP
      - "1514:1514"
      # Syslog UDP"
      - "1514:1514/udp"
      # GELF TCP
      - "12201:12201"
      # GELF UDP
      - "12201:12201/udp"

volumes:
  postgres_data:
    driver: local
  mongo_data:
    driver: local
  graylog_data:
    driver: local
  es_data:
    driver: local

networks:
  my_network:
    driver: bridge

