version: '3.8'
services:
  postgres:
    image: postgres:15-alpine  # Χρησιμοποιούμε το lightweight Alpine image
    container_name: postgres-container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=YourStrong!Password123
      - POSTGRES_DB=customer_db
    ports:
      - "5432:5432"
    volumes:
      - ../Database/schema.sql:/docker-entrypoint-initdb.d/schema.sql  # Το init.sql αρχείο θα εκτελείται αυτόματα
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge
