global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'webapi'
    static_configs:
      - targets: ['host.docker.internal:5000'] # Το Web API endpoint
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
